version: "2"
services:
  api:
    build: ./api/app
    image: cat_api
    container_name: cat_api
    links:
      - mongo
    ports:
      - 3005:3005
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: cat_mongo
    ports:
    - 27017:27017
  nginx:
    image: nginx
    container_name: cat_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
    ports:
      - 83:80
    depends_on:
      - api

#volumes:
#  esdata:
