version: "2"
services:
  api:
    build: ./api/
    image: cat_api
    container_name: cat_api
    links:
      - mongo
    ports:
      - 3005:3005
    depends_on:
      - mongo
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
#    container_name: cat-elasticsearch
#    volumes:
#      - ./esdata:/usr/share/elasticsearch/data
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - discovery.type=single-node
#    ports:
#    - "9300:9300"
#    - "9200:9200"
  mongo:
    image: mongo
    container_name: cat_mongo
    ports:
    - 27017:27017
  nginx:
    image: nginx
    container_name: cat_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
    ports:
      - 83:80
    depends_on:
      - api

#volumes:
#  esdata:
